--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.1

-- Started on 2022-01-20 21:23:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 17284)
-- Name: History; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."History" (
    "HistoryID" integer NOT NULL,
    "timeLogin" timestamp without time zone NOT NULL,
    "timeLogout" timestamp without time zone,
    "userID" integer NOT NULL
);


ALTER TABLE public."History" OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 17283)
-- Name: History_HistoryID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."History" ALTER COLUMN "HistoryID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."History_HistoryID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 17290)
-- Name: Hopital; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Hopital" (
    "hopitalID" integer NOT NULL,
    "hopitalName" character varying(100) NOT NULL,
    "current_Quantity" integer NOT NULL,
    "Capacity" integer NOT NULL,
    province character varying(100) NOT NULL,
    ward character varying(100) NOT NULL,
    "District" character varying(100) NOT NULL
);


ALTER TABLE public."Hopital" OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 17289)
-- Name: Hopital_hopitalID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Hopital" ALTER COLUMN "hopitalID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Hopital_hopitalID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17366)
-- Name: Notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Notification" (
    "notificationID" integer NOT NULL,
    info character varying(100) NOT NULL,
    "userID" integer NOT NULL,
    "userName" character varying(100)
);


ALTER TABLE public."Notification" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17365)
-- Name: Notification_notificationID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Notification" ALTER COLUMN "notificationID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notification_notificationID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 17304)
-- Name: Order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Order" (
    "orderID" integer NOT NULL,
    "patientID" integer NOT NULL,
    "TotalPrice" integer NOT NULL,
    "oderDate" timestamp without time zone NOT NULL,
    "statusPayment" character varying(200)
);


ALTER TABLE public."Order" OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 17303)
-- Name: Order_orderID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Order" ALTER COLUMN "orderID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Order_orderID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 17310)
-- Name: OrdersDetail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrdersDetail" (
    "OrdersDetailID" integer NOT NULL,
    "OrdersID" integer NOT NULL,
    "PackageID" integer NOT NULL,
    "Quantity" integer NOT NULL
);


ALTER TABLE public."OrdersDetail" OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 17309)
-- Name: OrdersDetail_OrdersDetailID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OrdersDetail" ALTER COLUMN "OrdersDetailID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrdersDetail_OrdersDetailID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 17316)
-- Name: OrdersPackageDetail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrdersPackageDetail" (
    "OPDID" integer NOT NULL,
    "OrdersDetailID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" integer NOT NULL,
    "Unit" character varying(50) NOT NULL
);


ALTER TABLE public."OrdersPackageDetail" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17315)
-- Name: OrdersPackageDetail_OPDID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OrdersPackageDetail" ALTER COLUMN "OPDID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrdersPackageDetail_OPDID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17322)
-- Name: Package_Product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Package_Product" (
    "Package_ProductID" integer NOT NULL,
    "packageID" integer NOT NULL,
    "productID" integer NOT NULL,
    number integer,
    "isDelete" integer DEFAULT 0
);


ALTER TABLE public."Package_Product" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17321)
-- Name: Package_Product_Package_ProductID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Package_Product" ALTER COLUMN "Package_ProductID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Package_Product_Package_ProductID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17328)
-- Name: Patient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Patient" (
    "PatientID" integer NOT NULL,
    "PatientName" character varying(100) NOT NULL,
    "DOB" character varying NOT NULL,
    province character varying(100) NOT NULL,
    ward character varying(100) NOT NULL,
    "District" character varying(100) NOT NULL,
    "Status" character varying(10) NOT NULL,
    "userID" integer NOT NULL,
    "hospitalID" integer NOT NULL,
    patient_ref integer,
    "identityCard" character varying(50)
);


ALTER TABLE public."Patient" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17327)
-- Name: Patient_PatientID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Patient" ALTER COLUMN "PatientID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Patient_PatientID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17360)
-- Name: PaymentLimit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PaymentLimit" (
    "paymentLimitID" integer NOT NULL,
    value integer NOT NULL
);


ALTER TABLE public."PaymentLimit" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17359)
-- Name: PaymentLimit_paymentLimitID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PaymentLimit" ALTER COLUMN "paymentLimitID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PaymentLimit_paymentLimitID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17336)
-- Name: Product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Product" (
    "ProductID" integer NOT NULL,
    "Product_name" character varying(100) NOT NULL,
    price integer NOT NULL,
    "Unit" character varying(50) NOT NULL,
    "isDelete" integer,
    "Category" character varying(100),
    image1 character varying(1000) DEFAULT 0 NOT NULL,
    image2 character varying(1000),
    image3 character varying(1000)
);


ALTER TABLE public."Product" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17335)
-- Name: Product_ProductID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Product" ALTER COLUMN "ProductID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Product_ProductID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17342)
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    "userID" integer NOT NULL,
    "userName" character varying(100) NOT NULL,
    password character varying(200) NOT NULL,
    permission integer NOT NULL,
    active integer
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17341)
-- Name: User_userID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN "userID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_userID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 17447)
-- Name: historyPatient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."historyPatient" (
    "historyPatientID" integer NOT NULL,
    status character varying(100) NOT NULL,
    "patientID" integer NOT NULL,
    "hopitalID" integer NOT NULL,
    "fromDate" timestamp without time zone NOT NULL,
    "endDate" timestamp without time zone NOT NULL
);


ALTER TABLE public."historyPatient" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17451)
-- Name: historyPatient_historyPatientID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."historyPatient" ALTER COLUMN "historyPatientID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."historyPatient_historyPatientID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17354)
-- Name: productPackage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."productPackage" (
    "productPackageID" integer NOT NULL,
    "package_Name" character varying(100) NOT NULL,
    "limited_ProductQuantity" integer NOT NULL,
    "limited_PackageQuantity" integer NOT NULL,
    "limited_Time" integer NOT NULL,
    "isDelete" integer,
    image character varying(1000)
);


ALTER TABLE public."productPackage" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17353)
-- Name: productPackage_productPackageID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."productPackage" ALTER COLUMN "productPackageID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."productPackage_productPackageID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 3229 (class 2606 OID 17294)
-- Name: Hopital Hopital_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Hopital"
    ADD CONSTRAINT "Hopital_pkey" PRIMARY KEY ("hopitalID");


--
-- TOC entry 3249 (class 2606 OID 17370)
-- Name: Notification Notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notification"
    ADD CONSTRAINT "Notification_pkey" PRIMARY KEY ("notificationID");


--
-- TOC entry 3231 (class 2606 OID 17308)
-- Name: Order Order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT "Order_pkey" PRIMARY KEY ("orderID");


--
-- TOC entry 3233 (class 2606 OID 17314)
-- Name: OrdersDetail OrdersDetail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdersDetail"
    ADD CONSTRAINT "OrdersDetail_pkey" PRIMARY KEY ("OrdersDetailID");


--
-- TOC entry 3235 (class 2606 OID 17320)
-- Name: OrdersPackageDetail OrdersPackageDetail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdersPackageDetail"
    ADD CONSTRAINT "OrdersPackageDetail_pkey" PRIMARY KEY ("OPDID");


--
-- TOC entry 3227 (class 2606 OID 17288)
-- Name: History PK_history; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."History"
    ADD CONSTRAINT "PK_history" PRIMARY KEY ("HistoryID");


--
-- TOC entry 3241 (class 2606 OID 17340)
-- Name: Product PK_product; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Product"
    ADD CONSTRAINT "PK_product" PRIMARY KEY ("ProductID");


--
-- TOC entry 3243 (class 2606 OID 17346)
-- Name: User PK_user; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "PK_user" PRIMARY KEY ("userID");


--
-- TOC entry 3237 (class 2606 OID 17326)
-- Name: Package_Product Package_Product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Package_Product"
    ADD CONSTRAINT "Package_Product_pkey" PRIMARY KEY ("Package_ProductID");


--
-- TOC entry 3239 (class 2606 OID 17334)
-- Name: Patient Patient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patient"
    ADD CONSTRAINT "Patient_pkey" PRIMARY KEY ("PatientID");


--
-- TOC entry 3247 (class 2606 OID 17364)
-- Name: PaymentLimit PaymentLimit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PaymentLimit"
    ADD CONSTRAINT "PaymentLimit_pkey" PRIMARY KEY ("paymentLimitID");


--
-- TOC entry 3245 (class 2606 OID 17358)
-- Name: productPackage productPackage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."productPackage"
    ADD CONSTRAINT "productPackage_pkey" PRIMARY KEY ("productPackageID");


--
-- TOC entry 3251 (class 2606 OID 17391)
-- Name: Order FK_Order_patient; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT "FK_Order_patient" FOREIGN KEY ("patientID") REFERENCES public."Patient"("PatientID") NOT VALID;


--
-- TOC entry 3252 (class 2606 OID 17396)
-- Name: OrdersDetail FK_OrdersDetail_Orders; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdersDetail"
    ADD CONSTRAINT "FK_OrdersDetail_Orders" FOREIGN KEY ("OrdersID") REFERENCES public."Order"("orderID");


--
-- TOC entry 3253 (class 2606 OID 17401)
-- Name: OrdersDetail FK_OrdersDetail_Package; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdersDetail"
    ADD CONSTRAINT "FK_OrdersDetail_Package" FOREIGN KEY ("PackageID") REFERENCES public."productPackage"("productPackageID");


--
-- TOC entry 3254 (class 2606 OID 17406)
-- Name: OrdersPackageDetail FK_OrdersPackage_OrdersDetail; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdersPackageDetail"
    ADD CONSTRAINT "FK_OrdersPackage_OrdersDetail" FOREIGN KEY ("OrdersDetailID") REFERENCES public."OrdersDetail"("OrdersDetailID");


--
-- TOC entry 3255 (class 2606 OID 17411)
-- Name: OrdersPackageDetail FK_OrdersPackage_Product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdersPackageDetail"
    ADD CONSTRAINT "FK_OrdersPackage_Product" FOREIGN KEY ("ProductID") REFERENCES public."Product"("ProductID");


--
-- TOC entry 3250 (class 2606 OID 17376)
-- Name: History FK_history_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."History"
    ADD CONSTRAINT "FK_history_user" FOREIGN KEY ("userID") REFERENCES public."User"("userID") NOT VALID;


--
-- TOC entry 3260 (class 2606 OID 17371)
-- Name: Notification FK_notification_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notification"
    ADD CONSTRAINT "FK_notification_user" FOREIGN KEY ("userID") REFERENCES public."User"("userID") NOT VALID;


--
-- TOC entry 3256 (class 2606 OID 17416)
-- Name: Package_Product FK_package; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Package_Product"
    ADD CONSTRAINT "FK_package" FOREIGN KEY ("packageID") REFERENCES public."productPackage"("productPackageID") NOT VALID;


--
-- TOC entry 3258 (class 2606 OID 17426)
-- Name: Patient FK_patient_patient; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patient"
    ADD CONSTRAINT "FK_patient_patient" FOREIGN KEY (patient_ref) REFERENCES public."Patient"("PatientID") NOT VALID;


--
-- TOC entry 3259 (class 2606 OID 17431)
-- Name: Patient FK_patient_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patient"
    ADD CONSTRAINT "FK_patient_user" FOREIGN KEY ("userID") REFERENCES public."User"("userID") NOT VALID;


--
-- TOC entry 3257 (class 2606 OID 17421)
-- Name: Package_Product FK_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Package_Product"
    ADD CONSTRAINT "FK_product" FOREIGN KEY ("productID") REFERENCES public."Product"("ProductID") NOT VALID;


-- Completed on 2022-01-20 21:23:26

--
-- PostgreSQL database dump complete
--

